service: readability-api

provider:
  name: aws
  runtime: nodejs6.10
  versionFunctions: false
  memorySize: 512
  region: us-west-1

functions:
  getArticle:
    handler: handler.getArticle
    events:
      - http:
          path: article/{id}
          method: get
          cors: true
